name: Upload code coverage securely to Code Climate

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Receive PR"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/pr.zip', Buffer.from(download.data));
            
      - run: unzip pr.zip



      - name: 'Get and set commit time'
        uses: actions/github-script@0.3.0
        id: author-date
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var fs = require('fs');
            var commit_sha = String(fs.readFileSync('${{github.workspace}}/SHA', "utf8")).replace(/(\r\n|\n|\r)/gm, "");
            var owner = String(fs.readFileSync('${{github.workspace}}/OWNER', "utf8")).replace(/(\r\n|\n|\r)/gm, "");
            var repo = String(fs.readFileSync('${{github.workspace}}/REPO', "utf8")).replace(/(\r\n|\n|\r)/gm, "").split("/").pop();
            const commit_details = await github.git.getCommit({owner:owner, repo:repo , commit_sha:commit_sha});
            fs.writeFileSync('${{github.workspace}}/COMMITTED_AT', commit_details.data.author.date, { flag: 'w+' })
            console.log(commit_details.data.author.date)
            return new Date(commit_details.data.author.date).getTime() / 1000
             
      - run: echo ${{ steps.author-date.outputs.result }} was time committed.

      - name: Set ENV for codeclimate 
        run: |
          echo "GIT_BRANCH=$(cat ${{github.workspace}}/REF)" >> $GITHUB_ENV
          echo "GIT_COMMIT_SHA=$(cat ${{github.workspace}}/SHA)" >> $GITHUB_ENV
          echo "GIT_COMMITTED_AT=${{ steps.author-date.outputs.result }}" >> $GITHUB_ENV
          echo "REPO=$(cat ${{github.workspace}}/REPO)" >> $GITHUB_ENV
            
      - name: Upload to code climate
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE }}
        with:
          prefix: github.com/${{ env.REPO }}
          debug: true
          coverageLocations: |
              ${{github.workspace}}/pr/c.out:gocov
